// generated by @ng-toolkit/universal
const port = process.env.PORT || 3000;
const serverPath =  process.env.NODE_ENV === 'dev' ? './server/app/local-server.ts': './dist/server'
const server = require(serverPath);

server.app.listen(port, () => {
    console.log(`Listening on: http://localhost:${port}`);
});
